# Authentication Service Configuration
server:
  port: 8081

spring:
  application:
    name: auth-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/split_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# JWT Configuration
jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast64CharactersLongForHS512Algorithm1234567890
  expiration: 86400000

# Logging Configuration
logging:
  level:
    com.service.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true