# Balance Service Configuration
server:
  port: 8084

spring:
  application:
    name: balance-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/split_balance_db?createDatabaseIfNotExist=true
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Service Communication Configuration
services:
  auth-service:
    url: http://auth-service
  user-service:
    url: http://user-service
  transaction-service:
    url: http://transaction-service

# Business Rules Configuration
balance:
  rules:
    min-settlement-amount: 0.01    # Minimum amount for settlements
    auto-settle-threshold: 0.01    # Auto-settle amounts below this
    precision: 2                   # Decimal places for calculations
    optimization-enabled: true     # Enable balance optimization

# Logging Configuration
logging:
  level:
    com.service.balance: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true