# Transaction Service Configuration
server:
  port: 8083

spring:
  application:
    name: transaction-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/split_transaction_db?createDatabaseIfNotExist=true
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Service Communication Configuration
services:
  auth-service:
    url: http://auth-service
  user-service:
    url: http://user-service
  balance-service:
    url: http://balance-service

# Business Rules Configuration
transaction:
  rules:
    max-amount: 100000.00  # Maximum transaction amount
    min-amount: 0.01       # Minimum transaction amount
    max-participants: 20   # Maximum number of people in a transaction
    allow-future-dates: false  # Whether to allow future-dated transactions

# Logging Configuration
logging:
  level:
    com.service.transaction: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true