server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Enable service discovery integration
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Route Configuration - Define how requests are routed
      routes:
        # Auth Service Routes
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        # User Service Routes
        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        # Transaction Service Routes
        - id: transaction-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=2

        # Balance Service Routes
        - id: balance-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/balances/**
          filters:
            - StripPrefix=2

      # Enhanced CORS Configuration for Angular
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"     # Angular development server
              - "http://127.0.0.1:4200"     # Alternative localhost format
              - "http://localhost:3000"     # React (backup for testing)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
              - "X-Total-Count"
              - "X-Request-ID"
            allowCredentials: true
            maxAge: 3600

# Eureka Configuration (for registration only)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.service.gateway: DEBUG

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true