server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service Routes
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        # User Service Routes
        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        # Transaction Service Routes
        - id: transaction-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=2

        # Balance Service Routes
        - id: balance-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/balances/**
          filters:
            - StripPrefix=2

# Eureka Configuration (for registration only)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true