# Simple User Service Configuration
server:
  port: 8082

spring:
  application:
    name: user-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/split_user_db?createDatabaseIfNotExist=true
    username: root
    password: 11111111  # Change this to your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Service Communication Configuration
services:
  auth-service:
    url: http://auth-service  # This will be resolved by Eureka

# Logging
logging:
  level:
    com.service.user: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true