# Eureka Server Configuration
server:
  port: 8761  # Standard port for Eureka Server

spring:
  application:
    name: eureka-server

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
  client:
    # Since this IS the eureka server, it doesn't need to register with itself
    register-with-eureka: false
    # Since this IS the eureka server, it doesn't need to fetch registry from itself
    fetch-registry: false
    service-url:
      # This is where other services will connect to register themselves
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Disable self-preservation mode for development (not recommended for production)
    enable-self-preservation: false
    # How often to remove services that haven't sent heartbeat
    eviction-interval-timer-in-ms: 4000

# Logging configuration
logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG